### ISSUE TITLE
cool!

### ISSUE THREAD

**Issue by aquynh** [Cararasu/holodec#1]
this looks like a nice project, but it is hard to tell what you are doing. will you add a README?

keep it up, cheers!

**Comment by Cararasu** [comment]
Oh yeah, that's a good idea. I will.
Concerning the project, I aim to write a decompiler, but as you can see it is in a really early stage.

Btw. this is my first time using capstone and it is pretty amazing ;)

**Comment by aquynh** [comment]
nice, but your project description is still empty with "No description or website provided."

cheers.

**Comment by Biswa96** [comment]
@Cararasu need precompiled binary.
